"use client";

import { Plus, UserRound } from "lucide-react";
import { FormEvent, useState } from "react";

import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Field, Input, Select, Textarea } from "@/components/ui/form";
import { ErrorState, LoadingState } from "@/components/ui/states";
import { useToast } from "@/components/ui/toast";
import { useAuth } from "@/features/auth/auth-context";
import { useProject } from "@/features/projects/project-context";
import { useResource } from "@/hooks/use-resource";
import { api, jsonBody } from "@/services/api";
import type { Board, Sprint, Task, UserBrief } from "@/types/api";

export function KanbanBoard() {
  const { project } = useProject(); const { hasPermission } = useAuth(); const resource = useResource<Board>(`/projects/${project.id}/board`); const members = useResource<UserBrief[]>(`/projects/${project.id}/members`); const sprints = useResource<Sprint[]>(hasPermission("scrum.view") ? `/projects/${project.id}/sprints` : null); const { notify } = useToast();
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [dragged, setDragged] = useState<string>(); const [form, setForm] = useState({ title: "", description: "", type: "task", priority: "medium", assignee_id: "", sprint_id: "" });
  async function create(event: FormEvent) { event.preventDefault(); setSaving(true); try { await api(`/projects/${project.id}/tasks`, { method: "POST", body: jsonBody({ ...form, assignee_id: form.assignee_id || null, sprint_id: form.sprint_id || null }) }); setOpen(false); setForm({ title: "", description: "", type: "task", priority: "medium", assignee_id: "", sprint_id: "" }); notify("Task created"); await resource.reload(); } catch (reason) { notify((reason as Error).message, "error"); } finally { setSaving(false); } }
  async function drop(columnId: string) { if (!dragged) return; const previous = resource.data; if (previous) resource.setData({ ...previous, tasks: previous.tasks.map((task) => task.id === dragged ? { ...task, kanban_column_id: columnId } : task) }); try { await api(`/projects/${project.id}/board/tasks/${dragged}/move`, { method: "POST", body: jsonBody({ column_id: columnId }) }); await resource.reload(); } catch (reason) { resource.setData(previous); notify((reason as Error).message, "error"); } finally { setDragged(undefined); } }
  if (resource.loading) return <LoadingState label="Loading board…" />; if (resource.error || !resource.data) return <ErrorState message={resource.error ?? "Board unavailable"} retry={resource.reload} />;
  return <><div className="page-header"><div><h2>Kanban board</h2><p>Drag tasks between columns. Order and status are persisted.</p></div>{hasPermission("kanban.manage") ? <Button onClick={() => setOpen(true)}><Plus />Create task</Button> : null}</div><div className="kanban-board">{resource.data.columns.map((column) => { const tasks = resource.data!.tasks.filter((task) => task.kanban_column_id === column.id); return <section className="kanban-column" key={column.id} onDragOver={(event) => event.preventDefault()} onDrop={() => drop(column.id)}><div className="kanban-column-header"><span>{column.name}</span><span className="badge">{tasks.length}</span></div><div className="kanban-cards">{tasks.map((task) => <TaskCard task={task} key={task.id} draggable={hasPermission("kanban.manage")} onDrag={() => setDragged(task.id)} />)}</div></section>; })}</div><Dialog open={open} onOpenChange={setOpen} title="Create task"><form className="form-grid" onSubmit={create}><Field label="Title"><Input required autoFocus value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></Field><Field label="Description"><Textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></Field><div className="form-grid two"><Field label="Type"><Select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}><option value="task">Task</option><option value="story">Story</option><option value="bug">Bug</option><option value="epic">Epic</option></Select></Field><Field label="Priority"><Select value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })}><option value="lowest">Lowest</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="highest">Highest</option></Select></Field><Field label="Assignee"><Select value={form.assignee_id} onChange={(event) => setForm({ ...form, assignee_id: event.target.value })}><option value="">Unassigned</option>{members.data?.map((member) => <option value={member.id} key={member.id}>{member.first_name} {member.last_name}</option>)}</Select></Field><Field label="Sprint"><Select value={form.sprint_id} onChange={(event) => setForm({ ...form, sprint_id: event.target.value })}><option value="">Backlog</option>{sprints.data?.filter((sprint) => sprint.status === "planned" || sprint.status === "active").map((sprint) => <option value={sprint.id} key={sprint.id}>{sprint.name}</option>)}</Select></Field></div><div className="dialog-actions"><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button loading={saving}>Create task</Button></div></form></Dialog></>;
}

function TaskCard({ task, draggable, onDrag }: { task: Task; draggable: boolean; onDrag: () => void }) { return <article className="task-card" draggable={draggable} onDragStart={onDrag}><div className="split"><span className="mono small muted">{task.reference}</span><span className={`badge priority-${task.priority}`}>{task.priority}</span></div><div className="task-card-title">{task.title}</div><div className="task-card-meta"><span>{task.type}</span><span>{task.assignee ? <><UserRound /> {task.assignee.first_name}</> : "Unassigned"}</span></div></article>; }

